FROM golang:1.25.8-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/migrator ./cmd/migrate

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/migrator .
COPY --from=builder /app/migrations ./migrations
COPY --from=builder /app/config ./config

CMD ["./migrator"]