// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "backend-typing-trainer/internal/domain/models"
)

// AuthInputPort is an autogenerated mock type for the Auth type
type AuthInputPort struct {
	mock.Mock
}

type AuthInputPort_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthInputPort) EXPECT() *AuthInputPort_Expecter {
	return &AuthInputPort_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, login, password
func (_m *AuthInputPort) Login(ctx context.Context, login string, password string) (string, error) {
	ret := _m.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, login, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, login, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthInputPort_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthInputPort_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *AuthInputPort_Expecter) Login(ctx interface{}, login interface{}, password interface{}) *AuthInputPort_Login_Call {
	return &AuthInputPort_Login_Call{Call: _e.mock.On("Login", ctx, login, password)}
}

func (_c *AuthInputPort_Login_Call) Run(run func(ctx context.Context, login string, password string)) *AuthInputPort_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthInputPort_Login_Call) Return(token string, err error) *AuthInputPort_Login_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *AuthInputPort_Login_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *AuthInputPort_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, login, password, role
func (_m *AuthInputPort) Register(ctx context.Context, login string, password string, role models.UserRole) (*models.User, error) {
	ret := _m.Called(ctx, login, password, role)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, models.UserRole) (*models.User, error)); ok {
		return rf(ctx, login, password, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, models.UserRole) *models.User); ok {
		r0 = rf(ctx, login, password, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, models.UserRole) error); ok {
		r1 = rf(ctx, login, password, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthInputPort_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthInputPort_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
//   - role models.UserRole
func (_e *AuthInputPort_Expecter) Register(ctx interface{}, login interface{}, password interface{}, role interface{}) *AuthInputPort_Register_Call {
	return &AuthInputPort_Register_Call{Call: _e.mock.On("Register", ctx, login, password, role)}
}

func (_c *AuthInputPort_Register_Call) Run(run func(ctx context.Context, login string, password string, role models.UserRole)) *AuthInputPort_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(models.UserRole))
	})
	return _c
}

func (_c *AuthInputPort_Register_Call) Return(_a0 *models.User, _a1 error) *AuthInputPort_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthInputPort_Register_Call) RunAndReturn(run func(context.Context, string, string, models.UserRole) (*models.User, error)) *AuthInputPort_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthInputPort creates a new instance of AuthInputPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthInputPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthInputPort {
	mock := &AuthInputPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
