// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "backend-typing-trainer/internal/domain/models"

	uuid "github.com/google/uuid"
)

// DifficultyLevelsRepository is an autogenerated mock type for the Repository type
type DifficultyLevelsRepository struct {
	mock.Mock
}

type DifficultyLevelsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DifficultyLevelsRepository) EXPECT() *DifficultyLevelsRepository_Expecter {
	return &DifficultyLevelsRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, level
func (_m *DifficultyLevelsRepository) Create(ctx context.Context, level *models.DifficultyLevel) error {
	ret := _m.Called(ctx, level)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.DifficultyLevel) error); ok {
		r0 = rf(ctx, level)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DifficultyLevelsRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type DifficultyLevelsRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - level *models.DifficultyLevel
func (_e *DifficultyLevelsRepository_Expecter) Create(ctx interface{}, level interface{}) *DifficultyLevelsRepository_Create_Call {
	return &DifficultyLevelsRepository_Create_Call{Call: _e.mock.On("Create", ctx, level)}
}

func (_c *DifficultyLevelsRepository_Create_Call) Run(run func(ctx context.Context, level *models.DifficultyLevel)) *DifficultyLevelsRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.DifficultyLevel))
	})
	return _c
}

func (_c *DifficultyLevelsRepository_Create_Call) Return(_a0 error) *DifficultyLevelsRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DifficultyLevelsRepository_Create_Call) RunAndReturn(run func(context.Context, *models.DifficultyLevel) error) *DifficultyLevelsRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *DifficultyLevelsRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DifficultyLevelsRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type DifficultyLevelsRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *DifficultyLevelsRepository_Expecter) Delete(ctx interface{}, id interface{}) *DifficultyLevelsRepository_Delete_Call {
	return &DifficultyLevelsRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *DifficultyLevelsRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *DifficultyLevelsRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *DifficultyLevelsRepository_Delete_Call) Return(_a0 error) *DifficultyLevelsRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DifficultyLevelsRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *DifficultyLevelsRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *DifficultyLevelsRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.DifficultyLevel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.DifficultyLevel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.DifficultyLevel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.DifficultyLevel); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DifficultyLevel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DifficultyLevelsRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type DifficultyLevelsRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *DifficultyLevelsRepository_Expecter) GetByID(ctx interface{}, id interface{}) *DifficultyLevelsRepository_GetByID_Call {
	return &DifficultyLevelsRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *DifficultyLevelsRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *DifficultyLevelsRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *DifficultyLevelsRepository_GetByID_Call) Return(_a0 *models.DifficultyLevel, _a1 error) *DifficultyLevelsRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DifficultyLevelsRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.DifficultyLevel, error)) *DifficultyLevelsRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *DifficultyLevelsRepository) List(ctx context.Context, limit int, offset int) ([]*models.DifficultyLevel, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.DifficultyLevel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.DifficultyLevel, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.DifficultyLevel); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.DifficultyLevel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DifficultyLevelsRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type DifficultyLevelsRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *DifficultyLevelsRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *DifficultyLevelsRepository_List_Call {
	return &DifficultyLevelsRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *DifficultyLevelsRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *DifficultyLevelsRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *DifficultyLevelsRepository_List_Call) Return(_a0 []*models.DifficultyLevel, _a1 error) *DifficultyLevelsRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DifficultyLevelsRepository_List_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.DifficultyLevel, error)) *DifficultyLevelsRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, level
func (_m *DifficultyLevelsRepository) Update(ctx context.Context, level *models.DifficultyLevel) error {
	ret := _m.Called(ctx, level)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.DifficultyLevel) error); ok {
		r0 = rf(ctx, level)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DifficultyLevelsRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type DifficultyLevelsRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - level *models.DifficultyLevel
func (_e *DifficultyLevelsRepository_Expecter) Update(ctx interface{}, level interface{}) *DifficultyLevelsRepository_Update_Call {
	return &DifficultyLevelsRepository_Update_Call{Call: _e.mock.On("Update", ctx, level)}
}

func (_c *DifficultyLevelsRepository_Update_Call) Run(run func(ctx context.Context, level *models.DifficultyLevel)) *DifficultyLevelsRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.DifficultyLevel))
	})
	return _c
}

func (_c *DifficultyLevelsRepository_Update_Call) Return(_a0 error) *DifficultyLevelsRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DifficultyLevelsRepository_Update_Call) RunAndReturn(run func(context.Context, *models.DifficultyLevel) error) *DifficultyLevelsRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewDifficultyLevelsRepository creates a new instance of DifficultyLevelsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDifficultyLevelsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DifficultyLevelsRepository {
	mock := &DifficultyLevelsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
