// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "backend-typing-trainer/internal/domain/models"

	uuid "github.com/google/uuid"
)

// ExercisesRepository is an autogenerated mock type for the Repository type
type ExercisesRepository struct {
	mock.Mock
}

type ExercisesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ExercisesRepository) EXPECT() *ExercisesRepository_Expecter {
	return &ExercisesRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, exercise
func (_m *ExercisesRepository) Create(ctx context.Context, exercise *models.Exercise) error {
	ret := _m.Called(ctx, exercise)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Exercise) error); ok {
		r0 = rf(ctx, exercise)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExercisesRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ExercisesRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - exercise *models.Exercise
func (_e *ExercisesRepository_Expecter) Create(ctx interface{}, exercise interface{}) *ExercisesRepository_Create_Call {
	return &ExercisesRepository_Create_Call{Call: _e.mock.On("Create", ctx, exercise)}
}

func (_c *ExercisesRepository_Create_Call) Run(run func(ctx context.Context, exercise *models.Exercise)) *ExercisesRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Exercise))
	})
	return _c
}

func (_c *ExercisesRepository_Create_Call) Return(_a0 error) *ExercisesRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExercisesRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Exercise) error) *ExercisesRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ExercisesRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExercisesRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ExercisesRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ExercisesRepository_Expecter) Delete(ctx interface{}, id interface{}) *ExercisesRepository_Delete_Call {
	return &ExercisesRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ExercisesRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ExercisesRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ExercisesRepository_Delete_Call) Return(_a0 error) *ExercisesRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExercisesRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *ExercisesRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ExercisesRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Exercise, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Exercise
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Exercise, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Exercise); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Exercise)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExercisesRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ExercisesRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ExercisesRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ExercisesRepository_GetByID_Call {
	return &ExercisesRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ExercisesRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ExercisesRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ExercisesRepository_GetByID_Call) Return(_a0 *models.Exercise, _a1 error) *ExercisesRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExercisesRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Exercise, error)) *ExercisesRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *ExercisesRepository) List(ctx context.Context, limit int, offset int) ([]*models.Exercise, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Exercise
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Exercise, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.Exercise); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Exercise)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExercisesRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ExercisesRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *ExercisesRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *ExercisesRepository_List_Call {
	return &ExercisesRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *ExercisesRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *ExercisesRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *ExercisesRepository_List_Call) Return(_a0 []*models.Exercise, _a1 error) *ExercisesRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExercisesRepository_List_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.Exercise, error)) *ExercisesRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, exercise
func (_m *ExercisesRepository) Update(ctx context.Context, exercise *models.Exercise) error {
	ret := _m.Called(ctx, exercise)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Exercise) error); ok {
		r0 = rf(ctx, exercise)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExercisesRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ExercisesRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - exercise *models.Exercise
func (_e *ExercisesRepository_Expecter) Update(ctx interface{}, exercise interface{}) *ExercisesRepository_Update_Call {
	return &ExercisesRepository_Update_Call{Call: _e.mock.On("Update", ctx, exercise)}
}

func (_c *ExercisesRepository_Update_Call) Run(run func(ctx context.Context, exercise *models.Exercise)) *ExercisesRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Exercise))
	})
	return _c
}

func (_c *ExercisesRepository_Update_Call) Return(_a0 error) *ExercisesRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExercisesRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Exercise) error) *ExercisesRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewExercisesRepository creates a new instance of ExercisesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExercisesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExercisesRepository {
	mock := &ExercisesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
