// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "backend-typing-trainer/internal/domain/models"

	uuid "github.com/google/uuid"
)

// KeyboardZonesInputPort is an autogenerated mock type for the KeyboardZones type
type KeyboardZonesInputPort struct {
	mock.Mock
}

type KeyboardZonesInputPort_Expecter struct {
	mock *mock.Mock
}

func (_m *KeyboardZonesInputPort) EXPECT() *KeyboardZonesInputPort_Expecter {
	return &KeyboardZonesInputPort_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *KeyboardZonesInputPort) GetByID(ctx context.Context, id uuid.UUID) (*models.KeyboardZone, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.KeyboardZone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.KeyboardZone, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.KeyboardZone); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.KeyboardZone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeyboardZonesInputPort_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type KeyboardZonesInputPort_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *KeyboardZonesInputPort_Expecter) GetByID(ctx interface{}, id interface{}) *KeyboardZonesInputPort_GetByID_Call {
	return &KeyboardZonesInputPort_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *KeyboardZonesInputPort_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *KeyboardZonesInputPort_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *KeyboardZonesInputPort_GetByID_Call) Return(_a0 *models.KeyboardZone, _a1 error) *KeyboardZonesInputPort_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeyboardZonesInputPort_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.KeyboardZone, error)) *KeyboardZonesInputPort_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *KeyboardZonesInputPort) GetByName(ctx context.Context, name string) (*models.KeyboardZone, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *models.KeyboardZone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.KeyboardZone, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.KeyboardZone); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.KeyboardZone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeyboardZonesInputPort_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type KeyboardZonesInputPort_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *KeyboardZonesInputPort_Expecter) GetByName(ctx interface{}, name interface{}) *KeyboardZonesInputPort_GetByName_Call {
	return &KeyboardZonesInputPort_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *KeyboardZonesInputPort_GetByName_Call) Run(run func(ctx context.Context, name string)) *KeyboardZonesInputPort_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *KeyboardZonesInputPort_GetByName_Call) Return(_a0 *models.KeyboardZone, _a1 error) *KeyboardZonesInputPort_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeyboardZonesInputPort_GetByName_Call) RunAndReturn(run func(context.Context, string) (*models.KeyboardZone, error)) *KeyboardZonesInputPort_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *KeyboardZonesInputPort) List(ctx context.Context, limit int, offset int) ([]*models.KeyboardZone, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.KeyboardZone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.KeyboardZone, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.KeyboardZone); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.KeyboardZone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeyboardZonesInputPort_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type KeyboardZonesInputPort_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *KeyboardZonesInputPort_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *KeyboardZonesInputPort_List_Call {
	return &KeyboardZonesInputPort_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *KeyboardZonesInputPort_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *KeyboardZonesInputPort_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *KeyboardZonesInputPort_List_Call) Return(_a0 []*models.KeyboardZone, _a1 error) *KeyboardZonesInputPort_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeyboardZonesInputPort_List_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.KeyboardZone, error)) *KeyboardZonesInputPort_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewKeyboardZonesInputPort creates a new instance of KeyboardZonesInputPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyboardZonesInputPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyboardZonesInputPort {
	mock := &KeyboardZonesInputPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
