// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "backend-typing-trainer/internal/domain/models"

	uuid "github.com/google/uuid"
)

// StatisticsInputPort is an autogenerated mock type for the Statistics type
type StatisticsInputPort struct {
	mock.Mock
}

type StatisticsInputPort_Expecter struct {
	mock *mock.Mock
}

func (_m *StatisticsInputPort) EXPECT() *StatisticsInputPort_Expecter {
	return &StatisticsInputPort_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, statistic
func (_m *StatisticsInputPort) Create(ctx context.Context, statistic *models.Statistic) error {
	ret := _m.Called(ctx, statistic)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Statistic) error); ok {
		r0 = rf(ctx, statistic)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StatisticsInputPort_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type StatisticsInputPort_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - statistic *models.Statistic
func (_e *StatisticsInputPort_Expecter) Create(ctx interface{}, statistic interface{}) *StatisticsInputPort_Create_Call {
	return &StatisticsInputPort_Create_Call{Call: _e.mock.On("Create", ctx, statistic)}
}

func (_c *StatisticsInputPort_Create_Call) Run(run func(ctx context.Context, statistic *models.Statistic)) *StatisticsInputPort_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Statistic))
	})
	return _c
}

func (_c *StatisticsInputPort_Create_Call) Return(_a0 error) *StatisticsInputPort_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StatisticsInputPort_Create_Call) RunAndReturn(run func(context.Context, *models.Statistic) error) *StatisticsInputPort_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByExerciseID provides a mock function with given fields: ctx, exerciseID, limit, offset
func (_m *StatisticsInputPort) ListByExerciseID(ctx context.Context, exerciseID uuid.UUID, limit int, offset int) ([]*models.Statistic, error) {
	ret := _m.Called(ctx, exerciseID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByExerciseID")
	}

	var r0 []*models.Statistic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*models.Statistic, error)); ok {
		return rf(ctx, exerciseID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*models.Statistic); ok {
		r0 = rf(ctx, exerciseID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Statistic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, exerciseID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatisticsInputPort_ListByExerciseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByExerciseID'
type StatisticsInputPort_ListByExerciseID_Call struct {
	*mock.Call
}

// ListByExerciseID is a helper method to define mock.On call
//   - ctx context.Context
//   - exerciseID uuid.UUID
//   - limit int
//   - offset int
func (_e *StatisticsInputPort_Expecter) ListByExerciseID(ctx interface{}, exerciseID interface{}, limit interface{}, offset interface{}) *StatisticsInputPort_ListByExerciseID_Call {
	return &StatisticsInputPort_ListByExerciseID_Call{Call: _e.mock.On("ListByExerciseID", ctx, exerciseID, limit, offset)}
}

func (_c *StatisticsInputPort_ListByExerciseID_Call) Run(run func(ctx context.Context, exerciseID uuid.UUID, limit int, offset int)) *StatisticsInputPort_ListByExerciseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *StatisticsInputPort_ListByExerciseID_Call) Return(_a0 []*models.Statistic, _a1 error) *StatisticsInputPort_ListByExerciseID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StatisticsInputPort_ListByExerciseID_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*models.Statistic, error)) *StatisticsInputPort_ListByExerciseID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByLevelID provides a mock function with given fields: ctx, levelID, limit, offset
func (_m *StatisticsInputPort) ListByLevelID(ctx context.Context, levelID uuid.UUID, limit int, offset int) ([]*models.Statistic, error) {
	ret := _m.Called(ctx, levelID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByLevelID")
	}

	var r0 []*models.Statistic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*models.Statistic, error)); ok {
		return rf(ctx, levelID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*models.Statistic); ok {
		r0 = rf(ctx, levelID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Statistic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, levelID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatisticsInputPort_ListByLevelID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByLevelID'
type StatisticsInputPort_ListByLevelID_Call struct {
	*mock.Call
}

// ListByLevelID is a helper method to define mock.On call
//   - ctx context.Context
//   - levelID uuid.UUID
//   - limit int
//   - offset int
func (_e *StatisticsInputPort_Expecter) ListByLevelID(ctx interface{}, levelID interface{}, limit interface{}, offset interface{}) *StatisticsInputPort_ListByLevelID_Call {
	return &StatisticsInputPort_ListByLevelID_Call{Call: _e.mock.On("ListByLevelID", ctx, levelID, limit, offset)}
}

func (_c *StatisticsInputPort_ListByLevelID_Call) Run(run func(ctx context.Context, levelID uuid.UUID, limit int, offset int)) *StatisticsInputPort_ListByLevelID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *StatisticsInputPort_ListByLevelID_Call) Return(_a0 []*models.Statistic, _a1 error) *StatisticsInputPort_ListByLevelID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StatisticsInputPort_ListByLevelID_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*models.Statistic, error)) *StatisticsInputPort_ListByLevelID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID, limit, offset
func (_m *StatisticsInputPort) ListByUserID(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]*models.Statistic, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*models.Statistic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*models.Statistic, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*models.Statistic); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Statistic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatisticsInputPort_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type StatisticsInputPort_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *StatisticsInputPort_Expecter) ListByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *StatisticsInputPort_ListByUserID_Call {
	return &StatisticsInputPort_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, limit, offset)}
}

func (_c *StatisticsInputPort_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *StatisticsInputPort_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *StatisticsInputPort_ListByUserID_Call) Return(_a0 []*models.Statistic, _a1 error) *StatisticsInputPort_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StatisticsInputPort_ListByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*models.Statistic, error)) *StatisticsInputPort_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewStatisticsInputPort creates a new instance of StatisticsInputPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatisticsInputPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatisticsInputPort {
	mock := &StatisticsInputPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
