// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	jwt "backend-typing-trainer/internal/domain/ports/output/jwt"

	mock "github.com/stretchr/testify/mock"

	models "backend-typing-trainer/internal/domain/models"

	uuid "github.com/google/uuid"
)

// TokenManager is an autogenerated mock type for the TokenManager type
type TokenManager struct {
	mock.Mock
}

type TokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenManager) EXPECT() *TokenManager_Expecter {
	return &TokenManager_Expecter{mock: &_m.Mock}
}

// NewToken provides a mock function with given fields: userID, role
func (_m *TokenManager) NewToken(userID uuid.UUID, role models.UserRole) (string, error) {
	ret := _m.Called(userID, role)

	if len(ret) == 0 {
		panic("no return value specified for NewToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, models.UserRole) (string, error)); ok {
		return rf(userID, role)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, models.UserRole) string); ok {
		r0 = rf(userID, role)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, models.UserRole) error); ok {
		r1 = rf(userID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenManager_NewToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewToken'
type TokenManager_NewToken_Call struct {
	*mock.Call
}

// NewToken is a helper method to define mock.On call
//   - userID uuid.UUID
//   - role models.UserRole
func (_e *TokenManager_Expecter) NewToken(userID interface{}, role interface{}) *TokenManager_NewToken_Call {
	return &TokenManager_NewToken_Call{Call: _e.mock.On("NewToken", userID, role)}
}

func (_c *TokenManager_NewToken_Call) Run(run func(userID uuid.UUID, role models.UserRole)) *TokenManager_NewToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(models.UserRole))
	})
	return _c
}

func (_c *TokenManager_NewToken_Call) Return(_a0 string, _a1 error) *TokenManager_NewToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenManager_NewToken_Call) RunAndReturn(run func(uuid.UUID, models.UserRole) (string, error)) *TokenManager_NewToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseToken provides a mock function with given fields: token
func (_m *TokenManager) ParseToken(token string) (*jwt.TokenClaims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseToken")
	}

	var r0 *jwt.TokenClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*jwt.TokenClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *jwt.TokenClaims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.TokenClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenManager_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type TokenManager_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//   - token string
func (_e *TokenManager_Expecter) ParseToken(token interface{}) *TokenManager_ParseToken_Call {
	return &TokenManager_ParseToken_Call{Call: _e.mock.On("ParseToken", token)}
}

func (_c *TokenManager_ParseToken_Call) Run(run func(token string)) *TokenManager_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TokenManager_ParseToken_Call) Return(_a0 *jwt.TokenClaims, _a1 error) *TokenManager_ParseToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenManager_ParseToken_Call) RunAndReturn(run func(string) (*jwt.TokenClaims, error)) *TokenManager_ParseToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenManager creates a new instance of TokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenManager {
	mock := &TokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
