// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "backend-typing-trainer/internal/domain/models"

	uuid "github.com/google/uuid"
)

// UsersInputPort is an autogenerated mock type for the Users type
type UsersInputPort struct {
	mock.Mock
}

type UsersInputPort_Expecter struct {
	mock *mock.Mock
}

func (_m *UsersInputPort) EXPECT() *UsersInputPort_Expecter {
	return &UsersInputPort_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UsersInputPort) GetByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersInputPort_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UsersInputPort_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *UsersInputPort_Expecter) GetByID(ctx interface{}, id interface{}) *UsersInputPort_GetByID_Call {
	return &UsersInputPort_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *UsersInputPort_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *UsersInputPort_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UsersInputPort_GetByID_Call) Return(_a0 *models.User, _a1 error) *UsersInputPort_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsersInputPort_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.User, error)) *UsersInputPort_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLogin provides a mock function with given fields: ctx, login
func (_m *UsersInputPort) GetByLogin(ctx context.Context, login string) (*models.User, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetByLogin")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersInputPort_GetByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLogin'
type UsersInputPort_GetByLogin_Call struct {
	*mock.Call
}

// GetByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *UsersInputPort_Expecter) GetByLogin(ctx interface{}, login interface{}) *UsersInputPort_GetByLogin_Call {
	return &UsersInputPort_GetByLogin_Call{Call: _e.mock.On("GetByLogin", ctx, login)}
}

func (_c *UsersInputPort_GetByLogin_Call) Run(run func(ctx context.Context, login string)) *UsersInputPort_GetByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UsersInputPort_GetByLogin_Call) Return(_a0 *models.User, _a1 error) *UsersInputPort_GetByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsersInputPort_GetByLogin_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *UsersInputPort_GetByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *UsersInputPort) List(ctx context.Context, limit int, offset int) ([]*models.User, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.User, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.User); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersInputPort_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type UsersInputPort_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *UsersInputPort_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *UsersInputPort_List_Call {
	return &UsersInputPort_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *UsersInputPort_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *UsersInputPort_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *UsersInputPort_List_Call) Return(_a0 []*models.User, _a1 error) *UsersInputPort_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsersInputPort_List_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.User, error)) *UsersInputPort_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewUsersInputPort creates a new instance of UsersInputPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersInputPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersInputPort {
	mock := &UsersInputPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
