// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/difficulty-levels": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DifficultyLevels"
                ],
                "summary": "Список уровней сложности",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Лимит",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список уровней сложности",
                        "schema": {
                            "$ref": "#/definitions/difficultylevels.difficultyLevelListResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/utils.InternalErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Доступно только администратору. Создает уровень сложности и связывает его с зонами клавиатуры.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DifficultyLevels"
                ],
                "summary": "Создание уровня сложности",
                "parameters": [
                    {
                        "description": "Difficulty level payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/difficultylevels.upsertDifficultyLevelRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Уровень сложности создан",
                        "schema": {
                            "$ref": "#/definitions/difficultylevels.difficultyLevelSingleResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/utils.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/difficulty-levels/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DifficultyLevels"
                ],
                "summary": "Получение уровня сложности по ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Difficulty level ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Уровень сложности",
                        "schema": {
                            "$ref": "#/definitions/difficultylevels.difficultyLevelSingleResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Уровень не найден",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/utils.InternalErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Доступно только администратору.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DifficultyLevels"
                ],
                "summary": "Удаление уровня сложности",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Difficulty level ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Уровень сложности удален"
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Уровень не найден",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/utils.InternalErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Доступно только администратору. Обновляет параметры уровня и связи с зонами клавиатуры.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DifficultyLevels"
                ],
                "summary": "Обновление уровня сложности",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Difficulty level ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Difficulty level payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/difficultylevels.upsertDifficultyLevelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Уровень сложности обновлен",
                        "schema": {
                            "$ref": "#/definitions/difficultylevels.difficultyLevelSingleResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Уровень не найден",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/utils.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Авторизация по логину и паролю",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная авторизация",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Неверные учётные данные",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/utils.InternalErrorResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Register payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Пользователь создан",
                        "schema": {
                            "$ref": "#/definitions/auth.registerResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Логин уже занят",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/utils.InternalErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
                }
            }
        },
        "auth.loginRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "example": "player_one"
                },
                "password": {
                    "type": "string",
                    "example": "secret"
                }
            }
        },
        "auth.registerRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "example": "player_one"
                },
                "password": {
                    "type": "string",
                    "example": "secret"
                }
            }
        },
        "auth.registerResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/auth.registerUserResponse"
                }
            }
        },
        "auth.registerUserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2026-03-22T21:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "22222222-2222-2222-2222-222222222222"
                },
                "login": {
                    "type": "string",
                    "example": "player_one"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.UserRole"
                        }
                    ],
                    "example": "user"
                }
            }
        },
        "difficultylevels.difficultyLevelListResponse": {
            "type": "object",
            "properties": {
                "difficulty_levels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/difficultylevels.difficultyLevelResponse"
                    }
                }
            }
        },
        "difficultylevels.difficultyLevelResponse": {
            "type": "object",
            "properties": {
                "allowed_mistakes": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "key_press_time": {
                    "type": "number"
                },
                "keyboard_zone_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "max_exercise_length": {
                    "type": "integer"
                },
                "min_exercise_length": {
                    "type": "integer"
                }
            }
        },
        "difficultylevels.difficultyLevelSingleResponse": {
            "type": "object",
            "properties": {
                "difficulty_level": {
                    "$ref": "#/definitions/difficultylevels.difficultyLevelResponse"
                }
            }
        },
        "difficultylevels.upsertDifficultyLevelRequest": {
            "type": "object",
            "required": [
                "keyboard_zone_ids"
            ],
            "properties": {
                "allowed_mistakes": {
                    "type": "integer",
                    "minimum": 0
                },
                "key_press_time": {
                    "type": "number"
                },
                "keyboard_zone_ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "max_exercise_length": {
                    "type": "integer"
                },
                "min_exercise_length": {
                    "type": "integer"
                }
            }
        },
        "models.UserRole": {
            "type": "string",
            "enum": [
                "admin",
                "user"
            ],
            "x-enum-varnames": [
                "UserRoleAdmin",
                "UserRoleUser"
            ]
        },
        "utils.ErrorCode": {
            "type": "string",
            "enum": [
                "INVALID_REQUEST",
                "UNAUTHORIZED",
                "NOT_FOUND",
                "FORBIDDEN",
                "CONFLICT",
                "LOGIN_EXISTS",
                "INTERNAL_ERROR"
            ],
            "x-enum-varnames": [
                "ErrorCodeInvalidRequest",
                "ErrorCodeUnauthorized",
                "ErrorCodeNotFound",
                "ErrorCodeForbidden",
                "ErrorCodeConflict",
                "ErrorCodeLoginExists",
                "ErrorCodeInternalError"
            ]
        },
        "utils.ErrorDetails": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/utils.ErrorCode"
                        }
                    ],
                    "example": "INVALID_REQUEST"
                },
                "message": {
                    "type": "string",
                    "example": "invalid request"
                }
            }
        },
        "utils.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/utils.ErrorDetails"
                }
            }
        },
        "utils.InternalErrorDetails": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/utils.ErrorCode"
                        }
                    ],
                    "example": "INTERNAL_ERROR"
                },
                "message": {
                    "type": "string",
                    "example": "internal server error"
                }
            }
        },
        "utils.InternalErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/utils.InternalErrorDetails"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT token в формате ` + "`" + `Bearer \u003ctoken\u003e` + "`" + `.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Typing Trainer Service API",
	Description:      "Backend API для сервиса клавиатурного тренажера.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
